##
# Ansible playbook for setting up a Django project on Ubuntu 12.04
#

---
- hosts: servers
  #user: root
  #user: morlandi
  #remote_user: root
  sudo: yes
  gather_facts: False

  roles:
    - { role: server_setup, tags: ['server_setup' ] }
    - { role: user, tags: ['user', ] }
    - { role: postgresql, tags: ['postgresql', ] }
    - { role: nginx, tags: ['nginx', ] }
    - { role: redis, tags: ['redis', ] }
    - { role: database, tags: ['database', ] }
    - { role: utils, tags: ['utils', ] }
    - { role: django, sudo: yes, sudo_user: "{{django.owner}}", tags: ['django', ] }
    # - { role: supervisor, tags: ['supervisor', ] }

  vars_files:
    - vars.yml

  handlers:
    - include: handlers.yml
